# Although Docker Compose creates a default network for all projects,
# we will specifically create and use one, for clarity.
networks:
  etwebnet:

volumes:
  db-data:

services:
  etweb:
    build:
      context: .
      target: finalsqlite
    volumes:
      - db-data:/app/appdata
    networks:
      - etwebnet
    ports:
      - 18080:8080
